services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
    env_file: .env
    network_mode: host
    volumes:
      - ./config:/config # optional
      - ./assets:/assets # optional
    ports:
      - 127.0.0.1:3000:3000  # optional, destination should match ${WEB_APP_PORT} variable above.
      - 69:69/udp
      - 8080:80  # optional, destination should match ${NGINX_PORT} variable above.
    restart: unless-stopped
  dhcp:
    build: .
    env_file: .env
    cap_add:
    - NET_ADMIN
    network_mode: host
    
    