services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
    network_mode: host
    environment:
      - MENU_VERSION=3.0.0 # optional
      - NGINX_PORT=80 # optional
      - WEB_APP_PORT=3000 # optional
    volumes:
      - ./config:/config # optional
      - ./assets:/assets # optional
    ports:
      - 127.0.0.1:3000:3000  # optional, destination should match ${WEB_APP_PORT} variable above.
      - 69:69/udp
      - 8080:80  # optional, destination should match ${NGINX_PORT} variable above.
    restart: unless-stopped
  dhcp:
    build: .
    cap_add:
    - NET_ADMIN
    network_mode: host
    
    